#' Simulate a blockchain
#'
#'
#' @param n the size of blockchain, i.e. the total number of blocks in the blockchain
#' @param attack_power the percentage of attacker's computing power
#' @param t1 the first time point of attack
#' @param t2 the second time point of attack
#' @param n_miners the number of miners
#' @param block_rate the block genration rate (blocks per sec)
#' @param block_size the block size (MB)
#' @param burn_in the burn in time points, in which period all blocks are generated by the genesis miner
#'
#' @return This function will return a list with the following components:
#'   \item{adj_mat}{The adjacent matrix of generated blockchain.}
#'   \item{block_info}{A list that contains information of blockchain and blocks.}
#'
#' @export
simulate_blockchain <- function(n, attack_power = 0, t1 = ceiling(1/3*n), t2 = ceiling(2/3*n), 
                                n_miners = 10000, block_rate = 1/600, block_size = 1,
                                n_genesis_blocks = 1, burn_in = n_genesis_blocks)
{
  if (n_genesis_blocks <= 1) n_genesis_blocks <- 1
  if (burn_in <= 1) burn_in <- 1
  
  block_info <- list()
  block_info$n_blocks <- n
  block_info$n_miners <- n_miners
  block_info$block_rate <- block_rate
  block_info$block_size <- block_size
  block_info$n_genesis_blocks <- n_genesis_blocks
  block_info$burn_in <- burn_in
  
  block_info$attack <- list()
  block_info$attack$power <- attack_power
  block_info$attack$t1 <- t1
  block_info$attack$t2 <- t2
  
  # miner label, F - normal miner, T - attacker
  block_info$miners <- runif(n_miners) < attack_power
  block_info$miners[1] <- 0

  block_info$labels <- matrix(0, nrow = n, ncol = 3)
  colnames(block_info$labels) <- c("Miner_ID", "Group_ID", "Public_Time")

  # block miners
  block_info$labels[, 1] <- sample.int(n_miners, n, replace = T)
  block_info$labels[1:burn_in, 1] <- sample(which(block_info$miners == 0), burn_in, replace = T)
  block_info$labels[1:n_genesis_blocks, 1] <- 1  # all genesis blocks are generated by the first miner
  
  # block groups: 0 - normal blocks, 1 - attacker blocks
  block_info$labels[, 2] <- block_info$miners[block_info$labels[, 1]]

  # block public time: 0 - hidden blocks, >0 - publish time
  block_info$labels[, 3] <- 1:n
  block_info$labels[1:t2, 3][block_info$labels[1:t2, 2] == 1] <- t2

  block_info$visible_probs <- block_visible_probs(n, block_rate, block_size) 

  A <- matrix(0, nrow = n, ncol = n)
  for (i in 2:n)
  {
    if (block_info$labels[i, 2] == 0)
    {
      A[i, link_block_normal(i, A, block_info)] <- 1
    }
    else
    {
      A[i, link_block_attack(i, A, block_info)] <- 1
    }
  }
# return adjacent matrix of blockchain
  list(adj_mat = A, block_info = block_info)
}


link_block_normal <- function(i, A, block_info)
{
  v <- block_visible(i, block_info)
  v <- block_visible_adjust(v, A)
  block_tips(v, A)
}


link_block_attack <- function(i, A, block_info)
{
  links <- numeric()
  if (i < block_info$attack$t1)
  {
    links <- link_block_normal(i, A, block_info)
  }
  j <- which(block_info$labels[1:(i-1), 2] == 1)
  if (length(j) > 0)
  {
    links <- union(links, max(j))
  }
  links
}


block_visible_probs <- function(n, block_rate = 1/600, block_size = 1, band_width = 512)
{
  shape <- 2
  delay <- block_size * 1024 * 8 / band_width
  scale <- delay/(shape-1)
  pgamma((1:n)/block_rate, shape=shape, scale=scale, lower.tail = T, log.p = F)
}


# i: block id of new block
block_visible <- function(i, block_info)
{
  t <- i - block_info$labels[1:(i-1), 3]
  p <- numeric(i-1)
  p[t <= 0] <- 0
  p[t > 0] <- block_info$visible_probs[t[t > 0]]
  p[1] <- 1
  p[block_info$labels[1:(i-1), 1] == block_info$labels[i, 1]] <- 1
  which(runif(i-1) < p)
}


# v: the visibility status of block 1:(i-1) for block i
# A: the current adjacent matrix before block i is added
block_visible_adjust <- function(v, A)
{
  v0 <- v
  v1 <- v
  while (length(v1) > 0) {
    v1 <- which(colSums(A[v1, , drop = F]) > 0)
    v1 <- setdiff(v1, v0)
    v0 <- union(v0, v1)
  }
# return the adjusted visible status of block 1:(i-1)
  v0
}


block_tips <- function(v, A)
{
  v[which(colSums(A[v, v, drop = F]) == 0)]
}
